# Generated by Django 2.2.3 on 2019-08-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190805_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
