# Generated by Django 2.2.3 on 2019-08-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tag_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='type',
            new_name='tag_type',
        ),
        migrations.AddField(
            model_name='link',
            name='tag',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
