# Generated by Django 2.2.3 on 2019-08-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190806_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='tag',
            new_name='tags',
        ),
    ]
